import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { z } from "zod";

const schema = z.object({
  title: z.string(),
  channel: z.string(),
  duration: z.number().optional(),
  verdict: z.object({ text: z.string(), tags: z.array(z.string()) }).optional(),
  takeaways: z.object({ items: z.array(z.object({ text: z.string(), timestamp: z.string() })) }).optional(),
  steps: z.object({ items: z.array(z.string()) }).optional(),
});

export async function POST(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await req.json();
    const data = schema.parse(body);

    let md = `# ${data.title}\n`;
    md += `**${data.channel}**`;
    if (data.duration) {
      const m = Math.floor(data.duration / 60);
      md += ` · ${m} min`;
    }
    md += `\n\n---\n\n`;

    if (data.verdict) {
      md += `## Verdict\n\n${data.verdict.text}\n\n`;
      if (data.verdict.tags.length > 0) {
        md += `**Covers:** ${data.verdict.tags.join(", ")}\n\n`;
      }
    }

    if (data.takeaways) {
      md += `## Key Takeaways\n\n`;
      data.takeaways.items.forEach((item, i) => {
        md += `${i + 1}. ${item.text} *(${item.timestamp})*\n`;
      });
      md += `\n`;
    }

    if (data.steps) {
      md += `## Action Steps\n\n`;
      data.steps.items.forEach((step, i) => {
        md += `${i + 1}. ${step}\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by [Recall](https://getrecall.app)*\n`;

    return NextResponse.json({ markdown: md });
  } catch {
    return NextResponse.json({ error: "Failed to export" }, { status: 500 });
  }
}
