import { BlogPost } from "@/components/ui/blog-card";

export interface BlogPostWithBody extends BlogPost {
  body: { type: "p" | "h2" | "h3" | "quote"; text: string }[];
}

export const posts: BlogPostWithBody[] = [
  {
    slug: "stop-wasting-time-on-youtube",
    title: "How I stopped wasting 6 hours a week on YouTube",
    excerpt: "I tracked my YouTube habits for a month. The results were embarrassing, but they led me to a workflow that actually respects my time.",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80",
    author: { name: "Alex Chen", avatar: "", initials: "AC" },
    date: "Mar 22, 2026",
    readTime: "6 min read",
    tags: ["Productivity", "YouTube"],
    body: [
      { type: "p", text: "I didn\'t think I had a YouTube problem. I\'m not the kind of person who falls into rabbit holes of reaction videos or drama channels. I watch \"productive\" content: coding tutorials, design breakdowns, business strategy. The good stuff." },
      { type: "p", text: "Then I installed a screen time tracker. After one month, the numbers were brutal: 6 hours and 14 minutes per week on YouTube. That\'s more than 320 hours a year. An entire month of waking hours, spent watching other people explain things." },
      { type: "h2", text: "The real problem wasn\'t the watching" },
      { type: "p", text: "Time spent watching wasn\'t the issue. The issue was that I couldn\'t recall 90% of what I\'d watched. I\'d finish a 40-minute tutorial feeling smart, and within 48 hours I couldn\'t tell you three things from it. All that time, effectively wasted." },
      { type: "p", text: "I tried taking notes. That helped a little, but it turned every video into a chore. I\'d pause, scribble, rewind, pause again. A 20-minute video would take 45 minutes, and my notes were messy and incomplete." },
      { type: "h2", text: "The workflow that changed everything" },
      { type: "p", text: "I started using Recall about six weeks ago, and the shift was immediate. Instead of watching a video and hoping something sticks, I paste the link and get a structured summary before I even hit play." },
      { type: "p", text: "Here\'s my actual workflow now: First, I paste the URL and use \"Worth my time?\" mode. If the verdict says it\'s relevant, I skim the key takeaways. If something looks interesting, I click the timestamp and watch just that section. If I need to actually do something, I switch to step-by-step mode." },
      { type: "h2", text: "The results after 6 weeks" },
      { type: "p", text: "My YouTube time dropped from 6 hours to about 2.5 hours per week. But here\'s the thing: I\'m actually learning more. Because I\'m only watching the parts that matter, and I have a summary to reference later, the retention is dramatically better." },
      { type: "p", text: "I saved roughly 3.5 hours per week. That\'s 182 hours per year. I\'m using that time to actually build things instead of watching other people build things." },
      { type: "h2", text: "What I\'d tell my past self" },
      { type: "p", text: "Don\'t stop watching YouTube. It\'s genuinely one of the best learning resources ever created. But stop watching it passively. Get a system that respects your time, gives you the key ideas upfront, and lets you decide what\'s worth your attention." },
      { type: "p", text: "The irony is that by watching less, I\'m getting more from every minute I do spend watching." },
    ],
  },
  {
    slug: "ai-summaries-vs-manual-notes",
    title: "AI summaries vs manual notes: which actually helps you learn?",
    excerpt: "We compared retention rates between AI-generated summaries and hand-written notes across 200 students. The answer surprised us.",
    image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&q=80",
    author: { name: "Dr. Sarah Kim", avatar: "", initials: "SK" },
    date: "Mar 18, 2026",
    readTime: "8 min read",
    tags: ["Research", "Learning"],
    body: [
      { type: "p", text: "There\'s a long-standing belief in education that the act of writing notes by hand is what makes them effective. The \"generation effect\", the idea that producing information yourself leads to better retention, has been well-documented since the 1970s." },
      { type: "p", text: "So when AI-generated summaries started becoming popular, educators were skeptical. If you\'re not doing the cognitive work yourself, how could an AI summary possibly help you learn? We decided to test this empirically." },
      { type: "h2", text: "The study design" },
      { type: "p", text: "We recruited 200 university students and split them into four groups of 50. All groups watched the same three educational YouTube videos (total runtime: 87 minutes). The groups differed only in their note-taking method:" },
      { type: "p", text: "Group A took handwritten notes during the video. Group B typed notes during the video. Group C received AI-generated summaries (via Recall) after watching. Group D received AI-generated summaries before and after watching." },
      { type: "p", text: "We tested retention at three intervals: immediately after, one week later, and one month later. Tests included both factual recall and conceptual understanding questions." },
      { type: "h2", text: "The surprising results" },
      { type: "p", text: "At immediate recall, Group A (handwritten) performed best, followed closely by Group D (AI summaries before + after). No surprises there: the generation effect is real." },
      { type: "p", text: "But at one week and one month, something interesting happened. Group D overtook everyone. Their retention scores were 23% higher than Group A at the one-month mark. Group C (AI summaries after only) performed comparably to Group B (typed notes)." },
      { type: "h2", text: "Why AI summaries + watching outperformed pure note-taking" },
      { type: "p", text: "Our hypothesis: Group D had two advantages. First, the pre-watch summary gave them a framework: they knew what to listen for. Second, the post-watch summary served as a reference document they could revisit, which handwritten notes rarely are (let\'s be honest, most people never re-read their notes)." },
      { type: "p", text: "The AI summary also captured ideas that students missed while writing. Note-taking is inherently lossy: you can\'t write and listen simultaneously. The AI had access to the full transcript." },
      { type: "h2", text: "The takeaway" },
      { type: "p", text: "Handwritten notes are still valuable for initial encoding. But for long-term retention, having a well-structured reference document matters more. The best approach is probably a hybrid: use an AI summary as your scaffold, then annotate it with your own thoughts." },
      { type: "p", text: "The generation effect is real, but so is the reference effect. The students who had both, a reason to pay attention and a document to revisit, learned the most." },
    ],
  },
  {
    slug: "study-workflow-that-sticks",
    title: "The study workflow that actually sticks",
    excerpt: "Forget Pomodoro. Forget second brains. Here\'s a dead-simple system for turning YouTube lectures into lasting knowledge.",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80",
    author: { name: "Marcus Rivera", avatar: "", initials: "MR" },
    date: "Mar 14, 2026",
    readTime: "5 min read",
    tags: ["Study tips", "Workflow"],
    body: [
      { type: "p", text: "I\'ve tried every productivity system. Pomodoro timers, Zettelkasten, building a second brain, Cornell notes. They all work for about two weeks, then I stop. The overhead of maintaining the system becomes more work than the actual studying." },
      { type: "p", text: "After years of this, I\'ve landed on something that actually stuck. It\'s embarrassingly simple, which is probably why it works." },
      { type: "h2", text: "The 3-step system" },
      { type: "h3", text: "Step 1: Triage before you watch" },
      { type: "p", text: "Before committing 30-60 minutes to a video, paste the link into Recall and use \"Worth my time?\" mode. This takes 10 seconds and saves you from watching videos that sound relevant but aren\'t. I\'d estimate this alone saves me 2-3 hours per week." },
      { type: "h3", text: "Step 2: Watch with intent" },
      { type: "p", text: "If the video passes triage, pull up the key takeaways. Read them first. Now when you watch, you\'re not passively absorbing, you\'re actively looking for the ideas you already know are coming. This is called \"priming\" and it\'s one of the most effective learning techniques in cognitive science." },
      { type: "h3", text: "Step 3: Do something with it" },
      { type: "p", text: "After watching, switch to step-by-step mode. If the video taught you something practical, follow the action list. If it was more conceptual, use the follow-up question feature to test your understanding. Ask Recall to explain a concept in different terms, or to connect it to something you already know." },
      { type: "h2", text: "Why this works when other systems don\'t" },
      { type: "p", text: "Three reasons. First, there\'s zero setup. No notebooks to maintain, no apps to configure, no tags to organize. You paste a link and go. Second, it\'s built around the video, not around a separate system. You\'re not context-switching between your learning and your organization tool." },
      { type: "p", text: "Third, and most importantly: every step has an immediate payoff. Triage saves you time right now. Priming makes the video more interesting right now. The action list gives you something to do right now. There\'s no delayed gratification: each step rewards you immediately." },
      { type: "h2", text: "The compound effect" },
      { type: "p", text: "After three months of this, I looked at my Recall library and was shocked. I\'d processed over 150 videos. But more importantly, I could search through all of them. When I needed to remember how to set up a specific Docker configuration, I searched my library and found the exact timestamp from a video I\'d watched two months ago." },
      { type: "p", text: "That\'s the real power: not just learning better in the moment, but building a searchable knowledge base over time. Without ever organizing a single thing." },
    ],
  },
  {
    slug: "why-timestamps-matter",
    title: "Why timestamps are the most underrated learning tool",
    excerpt: "Jumping to the right moment in a video isn\'t just convenient. It fundamentally changes how your brain encodes information.",
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80",
    author: { name: "Emma Liu", avatar: "", initials: "EL" },
    date: "Mar 10, 2026",
    readTime: "4 min read",
    tags: ["Learning science", "Tips"],
    body: [
      { type: "p", text: "Think about how you use a textbook. You don\'t read it cover to cover every time you need to reference something. You use the index. You flip to the right chapter. You scan the headings until you find what you need." },
      { type: "p", text: "Video doesn\'t have an index. Until now, the only way to find a specific moment was to scrub through the timeline and hope you recognized the right frame. That\'s like using a textbook with no table of contents, no page numbers, and no headings." },
      { type: "h2", text: "What happens in your brain when you jump to a timestamp" },
      { type: "p", text: "When you read a takeaway like \"Grind size is the single highest-leverage variable\" and then click to watch the 90-second segment where the creator explains why, something powerful happens. You\'ve created what cognitive scientists call a \"retrieval cue.\" The text primes your brain with the concept, and the video provides the rich, multi-sensory encoding." },
      { type: "p", text: "This is fundamentally different from passively watching the same segment in context. When you watch the whole video linearly, that segment is just one of dozens of ideas competing for your attention. When you jump to it directly, it gets your full focus." },
      { type: "h2", text: "The spacing effect" },
      { type: "p", text: "Timestamps also enable a natural form of spaced repetition. You read the summary (first exposure), watch the segment (second exposure), and later search your library and re-read the takeaway (third exposure). Each time, the memory gets stronger." },
      { type: "p", text: "Without timestamps, there\'s no practical way to do this. You\'d have to rewatch entire videos to find the one moment you want to revisit. Nobody does that." },
      { type: "h2", text: "Practical tips" },
      { type: "p", text: "When you get a summary with timestamps, don\'t just read them. Click through at least the top 2-3. Watching even 60 seconds of the original video dramatically improves retention compared to reading the summary alone." },
      { type: "p", text: "If you\'re studying for an exam, go through your Recall library the night before and click through the key timestamps. It\'s the video equivalent of flipping through your flashcards, but with the added benefit of hearing the original explanation in the creator\'s voice." },
    ],
  },
  {
    slug: "weekly-digest-changed-everything",
    title: "How a weekly email changed the way I consume content",
    excerpt: "I used to watch videos and forget them instantly. Then I started getting a Sunday recap of everything I\'d learned that week.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    author: { name: "Tom Chen", avatar: "", initials: "TC" },
    date: "Mar 6, 2026",
    readTime: "5 min read",
    tags: ["Recall Pro", "Digest"],
    body: [
      { type: "p", text: "I\'m a content creator, which means I watch a lot of YouTube. Competitor analysis, trend research, learning new editing techniques. On a typical week, I\'ll watch 15-20 videos. By Sunday, I couldn\'t tell you what I watched on Monday." },
      { type: "p", text: "That changed when I started using Recall\'s weekly digest. Every Sunday morning, I get an email that recaps everything I summarized that week. Not just a list of titles, but a narrative that connects the dots." },
      { type: "h2", text: "What the digest actually looks like" },
      { type: "p", text: "It starts with stats: how many videos I processed, how much time I saved, how many themes emerged. Then it groups everything by topic. Last week, it told me I\'d watched 7 videos about short-form content strategy, 4 about color grading, and 3 about audience retention." },
      { type: "p", text: "For each theme, it synthesizes the key ideas across all the videos. \"All three color grading tutorials agreed that shooting in log is essential, but they disagreed on whether to use LUTs or manual curves. The most experienced creator recommended manual curves for consistency.\"" },
      { type: "p", text: "That synthesis is the killer feature. I couldn\'t do that manually. I\'d have to remember all 4 videos and compare them in my head. The digest does it automatically." },
      { type: "h2", text: "The unexpected benefit: self-awareness" },
      { type: "p", text: "After a few weeks of digests, I started noticing patterns in my own consumption. I was spending a disproportionate amount of time on gear reviews and almost no time on storytelling, which is the thing that actually makes content good. The digest made my blind spots visible." },
      { type: "p", text: "I adjusted my watching habits based on this. Now I deliberately seek out videos on topics the digest shows I\'m neglecting. It\'s like having a personal content advisor." },
      { type: "h2", text: "Is it worth the Pro upgrade?" },
      { type: "p", text: "I used Recall free for two weeks before upgrading. The free version is genuinely useful: unlimited summaries and all three modes. But the digest is what made me a paying customer. For $2.99/month, having a system that not only helps me learn from individual videos but shows me the bigger picture of what I\'m learning over time? That\'s a no-brainer." },
      { type: "p", text: "If you watch more than 5 videos a week for learning or work, the digest alone is worth the upgrade. If you watch fewer than that, the free tier is probably all you need." },
    ],
  },
  {
    slug: "from-passive-to-active-watching",
    title: "From passive watching to active learning in 3 steps",
    excerpt: "Most people watch YouTube on autopilot. Here\'s how to flip the switch and actually retain what you consume.",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80",
    author: { name: "Kira Reddy", avatar: "", initials: "KR" },
    date: "Mar 2, 2026",
    readTime: "7 min read",
    tags: ["Guide", "Learning"],
    body: [
      { type: "p", text: "There are two ways to watch a YouTube video. The first is passive: you hit play, you watch, you feel like you learned something, and within a week you\'ve forgotten almost everything. The second is active: you engage with the content, process it, and build it into your existing knowledge. Same video, completely different outcome." },
      { type: "p", text: "The difference isn\'t willpower or intelligence. It\'s method. Here are three concrete steps to switch from passive to active." },
      { type: "h2", text: "Step 1: Know what you\'re looking for before you press play" },
      { type: "p", text: "This is the single biggest lever. When you start a video with a question in mind, your brain activates what psychologists call a \"schema\": a mental framework that helps you organize incoming information. Without a question, information washes over you. With a question, it sticks." },
      { type: "p", text: "Practically, this means: before watching, read the summary. Identify the 2-3 ideas that are most relevant to you. Now you have questions: \"How does this work?\" \"Is this different from what I already know?\" \"Can I apply this?\"" },
      { type: "h2", text: "Step 2: Interrupt the flow" },
      { type: "p", text: "Passive watching is comfortable because it\'s uninterrupted. Active learning requires you to break that flow. Pause the video. Ask yourself: \"What did they just say? Do I agree? How does this connect to what I already know?\"" },
      { type: "p", text: "This feels annoying at first. It slows you down. But that friction is exactly what creates learning. The brain doesn\'t form strong memories from smooth, easy experiences. It forms them from moments of effort and engagement." },
      { type: "p", text: "Recall\'s follow-up feature is designed for this. When something confuses you, ask a question. When something surprises you, ask \"why?\". These moments of curiosity are where real learning happens." },
      { type: "h2", text: "Step 3: Close the loop" },
      { type: "p", text: "Learning isn\'t complete when the video ends. It\'s complete when you\'ve done something with the information. This could be as simple as telling someone what you learned, writing a one-sentence summary in your own words, or applying one idea from the video to your own work." },
      { type: "p", text: "The step-by-step mode exists for exactly this reason. If a video taught you how to do something, don\'t just nod along. Follow the action list. The gap between \"I understand this\" and \"I can do this\" is enormous, and the only way to cross it is by doing." },
      { type: "h2", text: "The 80/20 of active learning" },
      { type: "p", text: "You don\'t need to do all three steps for every video. For casual content, step 1 alone (reading the summary first) will dramatically improve retention. For important content, things you want to apply to your work or studies, do all three." },
      { type: "p", text: "The goal isn\'t to turn every YouTube session into a study session. It\'s to have a system so that when you do want to learn something, you actually learn it. The rest of the time, watch whatever you want. Just know the difference." },
    ],
  },
  {
    slug: "youtube-is-the-new-textbook",
    title: "YouTube is the new textbook. Treat it like one.",
    excerpt: "The best learning resource in history deserves better than passive consumption. Here is how to use YouTube like the reference tool it should be.",
    image: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&q=80",
    author: { name: "Priya Sharma", avatar: "", initials: "PS" },
    date: "Feb 26, 2026",
    readTime: "6 min read",
    tags: ["Opinion", "Learning"],
    body: [
      { type: "p", text: "There are more free lectures on YouTube than in every university library combined. MIT OpenCourseWare, Khan Academy, 3Blue1Brown, Veritasium. The depth and quality of educational content on YouTube is staggering." },
      { type: "p", text: "But we don't treat it like a learning resource. We treat it like television. We open the app, scroll until something catches our eye, watch it, and move on. No notes, no review, no system." },
      { type: "h2", text: "The textbook analogy" },
      { type: "p", text: "Imagine buying a university textbook, reading it cover to cover once, never highlighting anything, never revisiting a chapter, and then putting it on a shelf forever. That is how most people use educational YouTube." },
      { type: "p", text: "Textbooks work because they have structure: a table of contents, chapter summaries, indexes and review questions. They are designed to be referenced, not just read." },
      { type: "h2", text: "Giving YouTube the same structure" },
      { type: "p", text: "This is what Recall does. It turns an unstructured 40-minute video into something with the same affordances as a textbook: a summary you can skim, key concepts you can review, timestamps you can jump to, and follow-up questions you can test yourself with." },
      { type: "p", text: "The video itself becomes the rich media layer on top of a structured document. You get the best of both formats: the engagement of video and the reference-ability of text." },
      { type: "h2", text: "Building a personal curriculum" },
      { type: "p", text: "Once you start treating YouTube like a learning tool, something interesting happens. You start curating instead of browsing. You build playlists with intent. You process videos in batches by topic." },
      { type: "p", text: "Over time, your Recall library becomes a personal curriculum. Search for any topic and find not just one video, but every insight you have collected across dozens of videos. It is the compounding effect of structured learning." },
      { type: "h2", text: "The shift is small but powerful" },
      { type: "p", text: "You do not need to change what you watch. You just need to change how you interact with it. Paste the link before you press play. Read the summary. Watch with intent. That is it." },
      { type: "p", text: "YouTube is already the best learning platform ever built. It just needs a better reading mode." },
    ],
  },
];
