import { BlogPost } from "@/components/ui/blog-card";

export const posts: BlogPost[] = [
  {
    slug: "stop-wasting-time-on-youtube",
    title: "How I stopped wasting 6 hours a week on YouTube",
    excerpt: "I tracked my YouTube habits for a month. The results were embarrassing — but they led me to a workflow that actually respects my time.",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80",
    author: { name: "Alex Chen", avatar: "", initials: "AC" },
    date: "Mar 22, 2026",
    readTime: "6 min read",
    tags: ["Productivity", "YouTube"],
  },
  {
    slug: "ai-summaries-vs-manual-notes",
    title: "AI summaries vs manual notes: which actually helps you learn?",
    excerpt: "We compared retention rates between AI-generated summaries and hand-written notes across 200 students. The answer surprised us.",
    image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&q=80",
    author: { name: "Dr. Sarah Kim", avatar: "", initials: "SK" },
    date: "Mar 18, 2026",
    readTime: "8 min read",
    tags: ["Research", "Learning"],
  },
  {
    slug: "study-workflow-that-sticks",
    title: "The study workflow that actually sticks",
    excerpt: "Forget Pomodoro. Forget second brains. Here's a dead-simple system for turning YouTube lectures into lasting knowledge.",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80",
    author: { name: "Marcus Rivera", avatar: "", initials: "MR" },
    date: "Mar 14, 2026",
    readTime: "5 min read",
    tags: ["Study tips", "Workflow"],
  },
  {
    slug: "why-timestamps-matter",
    title: "Why timestamps are the most underrated learning tool",
    excerpt: "Jumping to the right moment in a video isn't just convenient — it fundamentally changes how your brain encodes information.",
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80",
    author: { name: "Emma Liu", avatar: "", initials: "EL" },
    date: "Mar 10, 2026",
    readTime: "4 min read",
    tags: ["Learning science", "Tips"],
  },
  {
    slug: "weekly-digest-changed-everything",
    title: "How a weekly email changed the way I consume content",
    excerpt: "I used to watch videos and forget them instantly. Then I started getting a Sunday recap of everything I'd learned that week.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    author: { name: "Tom Chen", avatar: "", initials: "TC" },
    date: "Mar 6, 2026",
    readTime: "5 min read",
    tags: ["Recall Pro", "Digest"],
  },
  {
    slug: "from-passive-to-active-watching",
    title: "From passive watching to active learning in 3 steps",
    excerpt: "Most people watch YouTube on autopilot. Here's how to flip the switch and actually retain what you consume.",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80",
    author: { name: "Kira Reddy", avatar: "", initials: "KR" },
    date: "Mar 2, 2026",
    readTime: "7 min read",
    tags: ["Guide", "Learning"],
  },
];
